[build]
  base = "2ND TRY PROTOFILE/TAFATEFO-cursor-check-for-new-image-updates-81f8/medo-main"
  command = "cd 'one part/my-protofile-main/project' && npm ci && npm run build"
  publish = "one part/my-protofile-main/project/dist"

[build.environment]
  NODE_VERSION = "20"
  NPM_VERSION = "10"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build.processing]
  skip_processing = false

[build.processing.css]
  bundle = true
  minify = true

[build.processing.js]
  bundle = true
  minify = true

# إعدادات إضافية للأمان
[build.ignore]
  command = "git diff --quiet HEAD^ HEAD -- ."
