[build]
  base = "2ND TRY PROTOFILE/TAFATEFO-cursor-check-for-new-image-updates-81f8/medo-main/one part/my-protofile-main/project"
  command = "npm install && npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
