name: Build Test
on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: '2ND TRY PROTOFILE/TAFATEFO-cursor-check-for-new-image-updates-81f8/medo-main/one part/my-protofile-main/project/package-lock.json'
        
    - name: Install dependencies
      run: |
        cd "2ND TRY PROTOFILE/TAFATEFO-cursor-check-for-new-image-updates-81f8/medo-main/one part/my-protofile-main/project"
        npm ci
        
    - name: Build project
      run: |
        cd "2ND TRY PROTOFILE/TAFATEFO-cursor-check-for-new-image-updates-81f8/medo-main/one part/my-protofile-main/project"
        npm run build
        
    - name: Test build output
      run: |
        if [ -d "2ND TRY PROTOFILE/TAFATEFO-cursor-check-for-new-image-updates-81f8/medo-main/one part/my-protofile-main/project/dist" ]; then
          echo "✅ Build successful - dist folder created"
          ls -la "2ND TRY PROTOFILE/TAFATEFO-cursor-check-for-new-image-updates-81f8/medo-main/one part/my-protofile-main/project/dist"
        else
          echo "❌ Build failed - no dist folder"
          exit 1
        fi
